development:
  admin_name: Admin
  admin_email: testsachin700@gmail.com
  admin_password: testsachin@123
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: 51e18d8e7b444f84d6ccd0ea1e8957be91e199698686cdb406961c1fab89c0e20227cbd3743f18af329657661f551c8ca2a44dd7b9f9856c205153ddc482e840
